---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

---
parsed_sample:
- HOTSPOT_RED_THRESHOLD: '125'
  HOTSPOT_TEMPERATURE_STATE: GREEN
  HOTSPOT_TEMPERATURE_VALUE: '46'
  HOTSPOT_YELLOW_THRESHOLD: '105'
  INLET_RED_THRESHOLD: '56'
  INLET_TEMPERATURE_STATE: GREEN
  INLET_TEMPERATURE_VALUE: '28'
  INLET_YELLOW_THRESHOLD: '46'
  SWITCH: '1'
  SWITCH_TEMPERATURE: OK

